# Generated by Django 5.1.5 on 2025-02-08 05:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_privatechat_group_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatgroup',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chatgroup',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
