# Generated by Django 5.1.5 on 2025-02-08 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_chatgroup_created_at_chatgroup_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatgroup',
            name='slug',
            field=models.SlugField(blank=True, max_length=150, unique=True),
        ),
    ]
