# Generated by Django 5.1.5 on 2025-02-09 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_chatgroup_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='privatechat',
            name='last_message_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
