# Generated by Django 5.1.5 on 2025-02-19 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_groupmessage_file_alter_groupmessage_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='privatemessage',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='files/'),
        ),
        migrations.AlterField(
            model_name='privatemessage',
            name='body',
            field=models.TextField(blank=True, null=True),
        ),
    ]
