# Generated by Django 5.1.5 on 2025-05-12 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0009_privatemessage_file_alter_privatemessage_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='privatemessage',
            name='file',
            field=models.URLField(blank=True, null=True),
        ),
    ]
