# Generated by Django 5.1.5 on 2025-05-12 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0010_alter_privatemessage_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupmessage',
            name='file',
            field=models.URLField(blank=True, null=True),
        ),
    ]
