# Generated by Django 5.1.5 on 2026-04-28 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0011_alter_groupmessage_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupmessage',
            name='is_encrypted',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='privatemessage',
            name='is_encrypted',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='groupmessage',
            name='body',
            field=models.TextField(blank=True, null=True),
        ),
    ]
