# Generated by Django 5.1.5 on 2025-05-12 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='post_image',
        ),
        migrations.AddField(
            model_name='post',
            name='post_image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
