# Generated by Django 5.1.5 on 2025-05-12 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_remove_post_post_image_post_post_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='profile_image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
